// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'core/models/code_chunk.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 2178362621138323829),
    name: 'CodeChunk',
    lastPropertyId: const obx_int.IdUid(4, 4576130694967564513),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4066362264294727122),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4899720634981242047),
        name: 'filePath',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(1, 6780821786197973203),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4293859892876724019),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4576130694967564513),
        name: 'embedding',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(2, 7407910167482088155),
        hnswParams: obx_int.ModelHnswParams(dimensions: 768),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 2178362621138323829),
    lastIndexId: const obx_int.IdUid(2, 7407910167482088155),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    CodeChunk: obx_int.EntityDefinition<CodeChunk>(
      model: _entities[0],
      toOneRelations: (CodeChunk object) => [],
      toManyRelations: (CodeChunk object) => {},
      getId: (CodeChunk object) => object.id,
      setId: (CodeChunk object, int id) {
        object.id = id;
      },
      objectToFB: (CodeChunk object, fb.Builder fbb) {
        final filePathOffset = fbb.writeString(object.filePath);
        final contentOffset = fbb.writeString(object.content);
        final embeddingOffset = fbb.writeListFloat32(object.embedding);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, filePathOffset);
        fbb.addOffset(2, contentOffset);
        fbb.addOffset(3, embeddingOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final filePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final embeddingParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 10, []);
        final object = CodeChunk(
          id: idParam,
          filePath: filePathParam,
          content: contentParam,
          embedding: embeddingParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [CodeChunk] entity fields to define ObjectBox queries.
class CodeChunk_ {
  /// See [CodeChunk.id].
  static final id = obx.QueryIntegerProperty<CodeChunk>(
    _entities[0].properties[0],
  );

  /// See [CodeChunk.filePath].
  static final filePath = obx.QueryStringProperty<CodeChunk>(
    _entities[0].properties[1],
  );

  /// See [CodeChunk.content].
  static final content = obx.QueryStringProperty<CodeChunk>(
    _entities[0].properties[2],
  );

  /// See [CodeChunk.embedding].
  static final embedding = obx.QueryHnswProperty<CodeChunk>(
    _entities[0].properties[3],
  );
}
